config/routes.rb
Rails.application.routes.draw do
  
  resources :translations

  root 'filterselection#index'
  
  get 'import' => 'translations#import'
  post 'upload_res_file' => 'translations#upload_res_file'

end

app/models/translation.rb
class Translation < ActiveRecord::Base
  def self.languages
    ['en', 'fi', 'se', 'no', 'dk', 'fl', 'fr', 'es', 'est', 'lat', 'lit', 'rus', 'it', 'cze', 'pol', 'prt', 'tur']
  end
  validates :text_id, length: {minimum: 5,
    message: "Text id must be at least 5 characters long" }
  validates :language, inclusion: { in: Translation.languages,
    message: "Language '%{value}' not recognized" }
  validates :text_id, uniqueness: { scope: :language,
    message: "The entry %{value} already exists for given language" }
  has_many :translation_histories

  def original
    begin
      Translation.select("text").from("translations").where("text_id = '#{text_id}'").where("language = 'en'").first()["text"]
    rescue
      "N/A"
    end
  end
end

app/models/translation_history.rb
class TranslationHistory < ActiveRecord::Base
  belongs_to :translation
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/filterselection_controller.rb
class FilterselectionController < ApplicationController
  def index
  end
end

app/controllers/translations_controller.rb
require 'file_parser'
class TranslationsController < ApplicationController

def new
end

def create
  if all_languages
    @translations = []
    Translation.languages.each do |l|
      creation_params = translation_params
      creation_params[:language] = l
      @translation = Translation.new(creation_params)
      @translation.save!
      @translations << @translation
    end
  else
    @translation = Translation.new(translation_params)
    @translation.save!
    @translations << @translation
  end
end

def is_number? string
  true if Float(string) rescue false
end

def show
  if is_number?(params[:id])
    show_by_id(params[:id])
  else
    show_by_text_id(params[:id])
  end
end

def show_by_id(id)
  #@translation = Translation.find(params[:id])
  @translation = Translation.select("translations.*, originals.text as original")
    .from("translations, translations as originals")
    .where("translations.id = #{id}")
    .where("translations.text_id = originals.text_id")
    .where("originals.language = 'en'")
    .first()
end

def show_by_text_id(id)
  @translations = Translation.select("translations.*, originals.text as original")
    .from("translations, translations as originals")
    .where("translations.text_id = '#{id}'")
    .where("translations.text_id = originals.text_id")
    .where("originals.language = 'en'")
  render "show_all_languages"
end

def edit
  @translation = Translation.find(params[:id])
  if @translation.text != params[:text]
    translationHistory = @translation.translation_histories.create({:text=>@translation.text})
    translationHistory.save!
    @translation.text = params[:text]
    @translation.save!
  end
  redirect_to @translation unless params[:api]
end

def index
  @translations = Translation.select("translations.*, originals.text as original")
    .from("translations, translations as originals").where("translations.text_id = originals.text_id")
    .where("originals.language = 'en'")
  if params[:languages]
    @translations = @translations.where("translations.language IN (?)", params[:languages])
  end
  if params[:filter] == 'untranslated'
    @translations = @translations.where("translations.text LIKE originals.text")
  elsif params[:filter] == 'translated'
    @translations = @translations.where("translations.text NOT LIKE originals.text")
  end
end

def import
  render 'import'
end

def upload_res_file
  uploaded_io = params[:res_file]
  file_type = params[:file_type]
  filename = uploaded_io.original_filename
  data = uploaded_io.read
  save_upload_to_file(data, filename)
  @translations = create_translations_from_upload(data, file_type)
  render 'index'
end

private
def save_upload_to_file(data, filename)
  target_dir = Rails.root.join('public', 'uploads')
  FileUtils.mkdir_p(target_dir) unless File.directory?(target_dir)
  File.open(timestamp_filename(target_dir.join(filename)), 'wb') do |file|
    file.write(data)
  end
end

def create_translations_from_upload(data, file_type)
  raise "Unknown file format" unless file_type == "res"
  translations = []
  parser = ::FileParser.new()
  parser.parse_each(data) do |t| 
    params[:translation] = t
    translation = Translation.new(translation_params)
    translation.save!
    translations << translation
  end
  translations
end

def timestamp_filename(file)
  dir  = File.dirname(file)
  base = File.basename(file, ".*")
  time = Time.now.strftime "%Y-%m-%d_%H%M%S"  # or format however you like
  ext  = File.extname(file)
  File.join(dir, "#{base}_#{time}#{ext}")
end

def all_languages
  params.require(:translation).permit(:all_languages)[:all_languages]
end

def translation_params
  params.require(:translation).permit(:text_id, :language, :text)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/filterselection_helper.rb
module FilterselectionHelper
end

app/helpers/translations_helper.rb
module TranslationsHelper
end

app/views/filterselection/index.html.erb
<h1>Translation list options</h1>

<form action="translations" method="get">
<table>
  <tr>
    <td>Select Language: </td>
    <td><% Translation.languages.each do |l| %>
      <input type="checkbox" name="languages[]" value="<%= l %>" /><%= l %><br/>
      <% end %>
      <input type="checkbox" name="" id="checkbox_all"/>All
    </td>
    <!--<td><select name="language"><option value="en">English</option><option value="fi">Finnish</option><option value="se">Swedish</select></td>-->
  </tr>
  <tr>
    <td>Show: </td>
    <td>
      <input type="radio" name="filter" value="all"/> All<br/>
      <input type="radio" name="filter" value="translated"/> Translated<br/>
      <input type="radio" name="filter" value="untranslated"/> Untranslated<br/>
    </td>
  </tr>
  <tr><td colspan=2><input type="submit" value="Submit"/></td></tr>
</table>
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Translation Service</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/translations/_editContainer.html.erb
<div class="editContainer">
  <%= hidden_field_tag "id",      translation.id,   :class => "idHolder" %>
  <%= text_field_tag   "newText", translation.text, :class => "translationInput" %>
</div>

app/views/translations/_translationContainer.html.erb
<div class="translationContainer">
  <span class="originalText"><%= translation.original %></span><br/>
  <span class="translationText"><%= translation.text %></span>
</div>

app/views/translations/_translationList.html.erb
<table>
   <tr>
     <th>Text ID</th>
     <th>Language</th>
     <th>Text</th>
   </tr>

   <% translations.each do |translation| %>
   <%= render 'translationListRow', translation: translation %>
   <% end %>
</table>

app/views/translations/_translationListRow.html.erb
<% tr_id = "#{translation.text_id}_#{translation.language}" %>
<tr id="<%= tr_id %>" class="<%= cycle('even','odd') %>">
  <td class="idContainer"><%= link_to translation.text_id, translation %></td>
  <td class="languageContainer"><%= translation.language %></td>
  <td>
    <%= render 'translationContainer', translation: translation %>
    <%= render 'editContainer', translation: translation %>
  </td>
  <td class="buttonContainer">
    <input type="button" class="edit" value="Edit"/>
    <input type="button" class="save" value="Save"/>
    <input type="button" class="cancel" value="Cancel"/>
    <%= image_tag "success.png", alt: "Success", class: "success", width: "16" %>
    <%= image_tag "fail.png", alt: "Failure", class: "fail", width: "16" %>
</tr>

app/views/translations/create.html.erb
<% if @error %>
<h1>Error when inserting to database!</h1>
<h2>Probably the specified text-id - language combination exists already.</h2>
<% else %>
<h1>Newly created translations (<%= @translations.count %>)</h1>
<%= render 'translationList' %>
<% end %>

app/views/translations/import.html.erb
<%= form_tag({action: :upload_res_file}, multipart: true) do %>
  <%= hidden_field_tag 'file_type', 'res' %>
  <%= file_field_tag 'res_file' %>
  <%= submit_tag("Upload") %>
<% end %>

app/views/translations/index.html.erb
<%= link_to "<- Back", controller: "filterselection" %>
<h1>Translations</h1>

<%= render 'translationList', translations: @translations %>

app/views/translations/new.html.erb
<%= form_for :translation, url: translations_path do |f| %>
  <p>
    <%= f.label :text_id %><br/>
    <%= f.text_field :text_id %>
  </p>
  <p>
    <%= f.label :language %><br/>
    <%= f.text_field :language %>
    <%= f.check_box "all_languages" %>
    Create stub for all languages
  </p>
  <p>
    <%= f.label :text %><br/>
    <%= f.text_field :text %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/translations/show.html.erb
<%= render 'translationList', translations: [@translation] %>
<%= link_to "Show all languages", @translation.text_id %>
<p>
  <strong>History:</strong>
  <table id="history">
    <tr>
      <th>Replaced at</th>
      <th>Text</th>
    </tr>
    <% @translation.translation_histories.all.reverse.each do |h| %>
    <tr class="<%= cycle('even','odd') %>">
      <td><%= h.created_at %></td><td><%= h.text %></td>
    </tr>
    <% end %>
  </table>
</p>

app/views/translations/show_all_languages.html.erb
<%= render 'translationList', translations: @translations %>

app/views/translations/upload_success.html.erb
<p>Upload successful.</p>